language: objective-c

compiler:
 - gcc
 - clang

before_install:
 - git clone --depth=1 https://github.com/mapnik/mapnik-packaging.git mapnik-packaging
 - cd mapnik-packaging && source build.sh

install:
 - build_osmium

before_script:
 - make test

script:
 - cd examples
 - make